#!/bin/bash

BASENAME=$(echo -n "$1" | sed 's%^.*/\([^/]*\)\.git$%\1%g')
PTH="pack/plugins/start/$BASENAME" 

git submodule add --depth 1 "$1" "$PTH" && git config -f .gitmodules submodule."$PTH".shallow true
